# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademark',
            name='tm2',
        ),
        migrations.RemoveField(
            model_name='trademark',
            name='tm3',
        ),
        migrations.RemoveField(
            model_name='trademark',
            name='tm4',
        ),
        migrations.RemoveField(
            model_name='trademark',
            name='tm5',
        ),
    ]
