# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20160805_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademark',
            name='tm1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
