# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='slideimage1',
            new_name='slideimage3',
        ),
        migrations.AddField(
            model_name='slide',
            name='slideimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slide',
            name='slideimage2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slide',
            name='slidetext2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slidetext3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
