# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20160817_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='slideimage',
            new_name='slideimage1',
        ),
    ]
